### PR TITLE
Add gitter as developer communication channel

### PR DESCRIPTION
**Pull request by Wavesonics**
I keep wishing I could shoot you guys some questions without creating a bunch of issues on Github.

So I created a Gitter channel thinking that might be a useful real time communication channel.

I added it to the README so people can find it. @piiertho @chippmann ect, I can make you guys admins on it if you think this is a good idea.

Further, @piiertho could setup the github integration in Gitter if you guys think it'd be useful.

It'd be kinda cool if we could get our own channel in the Godot Discord server, but I'm not sure who to talk to about that.

### CODE REVIEW

**Comment by chippmann** [comment]
@Wavesonics We already have a discord server for communication. But we didn't mention it until now anywhere and directly invited people. @piiertho Maybe now is a good time to add the discord invite link to the readme's?
To be honest I don't know gitter at all nor it's integration into github. Maybe it's something worth to discuss.
@piiertho what do you think?

**Comment by piiertho** [comment]
Hi ! Currently we're using discord, we have to add it to readme. Here is a link:
https://discord.gg/tZ5XpZ

**Comment by Wavesonics** [comment]
Oh yeah if you already have a discord that's better.

If you want I'll submit a different pr adding it to the readme?

**Comment by Wavesonics** [comment]
Closing, #25 adds discord instead.

**Pull request closed without merging**
