### PR TITLE
Add dark theme to the docs

### PR DESCRIPTION
**Pull request by halotroop2288**
I'm [blinded by the light](https://www.youtube.com/watch?v=Rzk3x3HZbJI) (theme)!

### CODE REVIEW

**Comment by chippmann** [comment]
@halotroop2288 but we already hve a dark theme?


You can toggle it in the top right corner.
Will review this later anyways though. Maybe yours is a nice joice.

**Comment by chippmann** [comment]
Hum. Just now i saw that you openened the pull request in this repo. Is that on purpose? Are you working with kotlin native @halotroop2288?

**Comment by halotroop2288** [comment]
> 

You are on the wrong site. This is the Native repo, not the JVM repo.
image

**Comment by halotroop2288** [comment]
> Hum. Just now i saw that you openened the pull request in this repo. Is that on purpose? Are you working with kotlin native @halotroop2288?

I was trying to read the docs to see if I wanted to use it, yes.
Not sure yet, though. I do like Kotlin, so I might in the future.

**Comment by halotroop2288** [comment]
CI build failed not because of my change but probably due to outdated mkdocs plugins.

Wait why are the build workflows running in the docs directory? `docs/` should be ignored for those workflows.

**Comment by chippmann** [comment]
@halotroop2288 But you read this part right?
https://github.com/utopia-rise/godot-kotlin-native#important-notes

I really do not recommend using this version of the binding.
Also we did not invest any time into this repo since about two years and everything here is pretty outdated. I believe we're not even on kotlin `1.4.x`.

Just use our jvm version. Its far more enjoyable to use and the performance is great. Also godot 4 is around the corner there.

**Comment by halotroop2288** [comment]
I'm not using Godot 4, and not considering using JVM.
Regardless, your docs should have a dark theme so people visiting the site don't get blinded. This goes for pretty much every website.

**Comment by chippmann** [comment]
I totally agree. But this project is sunsetted at this point. We're not investing time anymore into it atm.
I will look into this PR and its workflow later in detail but we'll not invest time to make it work. If we have to adjust workflows or update something else, that will be up to the contributer at this point.
This might change once we have more time, but for now it is what it is. No one of us maintainers still use this project. We all have moved on to the jvm variant.

Just out of curiosity; why is the jvm variant not a consideration?

**Pull request closed without merging**
