### PR TITLE
Master merge preparations

### LINKED ISSUE #169: [Master-Merge ToDo] ICalls crash
Tested with `Texture.resourcePath` and `Curve.getPointCount()` which call `_icall_String` and `_icall_Long` respectively.

TestNode:
```kotlin
@RegisterClass
class TestingClass : Node() {
    @IntRange(0, 20, 2, Range.OR_GREATER)
    @RegisterProperty
    var rangeInt = 1

    @RegisterProperty
    lateinit var texture: Texture

    @RegisterProperty
    lateinit var curve: Curve

    @RegisterFunction
    override fun _ready() {
        println("Property: ${this::rangeInt.name} -> $rangeInt")
        println("Property: ${this::texture.name} -> TexturePath: ${texture.resourcePath}")
        println("Property: ${this::curve.name} -> ${curve.getPointCount()} Points")
    }
}
```

both properties are assigned in the `Inspector`

Stacktracke:
```
OpenGL ES 3.0 Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.35.0, 5.4.52-1-MANJARO, LLVM 10.0.0)
 
Property: rangeInt -> 12
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3c3e0) [0x7f504d5af3e0] (??:0)
-- END OF BACKTRACE --
```

### PR DESCRIPTION
**Pull request by chippmann**
This draft PR is intended to be used by every maintainer to do preparations for the merge of `master-merge` into `master`:

Current ToDo List:

- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/192
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/191
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/190
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/189
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/188
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/187
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/186
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/184
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/194
- [x] Merge https://github.com/utopia-rise/godot-kotlin/pull/199
- [x] Fix #169
- [x] Set up CodeOwners
- [ ] ~~Set up linting with CodeStyle checks~~ Will be implemented later

Please add more if you see something that needs to be done before merging can happen.

### CODE REVIEW

**Comment by CedNaru** [comment]
Should we remove the "old" folder before merging ? It's not necessary anymore and we already tagged the current state of the master.

**Comment by piiertho** [comment]
I think we should resolve #195 before doing a release. This could be fixed after merge, but I think we should have the 3 desktop platforms before release of beta.

**Comment by chippmann** [comment]
@piiertho I agree. But merge != beta release. But at least testing can begin.

**Comment by chippmann** [comment]
@CedNaru , @piiertho  @raniejade I think #169 needs to be fixed before we can merge. One cannot really test anything if this bug still occurs. For example I'm not able to set a texture on a sprite through code. Which is pretty severe.

**Comment by chippmann** [comment]
Sorry made a rebase mistake which automatically closed this PR as there no more changes. Reopened it.

**Comment by chippmann** [comment]
Now included in `master-merge2`

**Pull request closed without merging**
