### PR TITLE
Up versions to 0.1.0-3.2

### PR DESCRIPTION
**Pull request by piiertho**
This change versions of all modules to 0.1.0-3.2 for first beta release.
@chippmann please review it carefully to be sure I did not miss any config :)

### CODE REVIEW

**Review by chippmann — CHANGES_REQUESTED** [review]
In the samples the gradle plugin version is still:
` classpath("org.godotengine.kotlin:godot-gradle-plugin:1.0.1")`
Same in the corresponding documentations.

**Comment by piiertho** [comment]
Oops missed it !

**Review by chippmann — APPROVED** [review]
Now i think everything is fine.
Thanks for the release work :-)

**Comment by chippmann** [comment]
I would say we can include the kotlin version bump in this pr as well? Remwmber to also bump the MpApt version.
https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/

**Comment by chippmann** [comment]
I restarted the failed job. It seems it was a connectivity issue on the linux build server. Not an error in the build.

**Pull request merged**
