### PR TITLE
Set source target compatibility to java 8

### PR DESCRIPTION
**Pull request by chippmann**
This should prevent the source code to be build for higher java versions when built locally, so it stays compatible with whatever java version the user is using to build he's games.

### CODE REVIEW

**Comment by CedNaru** [comment]
Simple change. Good for me.
But if the user still import the project in IDEA with the option to use a custom version of Java instead of the one defined in Gradle, building from Idea will fail like before right ?
We might need to write a little disclaimer in the readme.

**Comment by chippmann** [comment]
> Simple change. Good for me.
> But if the user still import the project in IDEA with the option to use a custom version of Java instead of the one defined in Gradle, building from Idea will fail like before right ?
> We might need to write a little disclaimer in the readme.

Maybe I'm not yet sure. I'm trying this first.

**Comment by chippmann** [comment]
@CedNaru No it seems to be fine. I set the jdk version to 13 in the IDE for all modules and the samples to 1.8 and it builds fine.

**Comment by chippmann** [comment]
Even though it is a small change, I want to have @piiertho 's review as well as he has some good knowledge as well regarding gradle.

**Review by piiertho — APPROVED** [review]
It's ok for me :)

**Pull request merged**
