### PR TITLE
Added discord to README

### PR DESCRIPTION
**Pull request by Wavesonics**
Removed gitter

### CODE REVIEW

**Review by chippmann — APPROVED** [review]
Thanks for adding it :-)
@piiertho if you are also ok with it you can merge it :-)

**Comment by piiertho** [comment]
Whoops, it's not permanent link, Can you change with this one ? https://discord.gg/qSU2EQs

**Review by piiertho — CHANGES_REQUESTED** [review]
Whoops, it's not permanent link, Can you change with this one ? https://discord.gg/qSU2EQs

**Comment by Wavesonics** [comment]
@piiertho there we go, updated the link

**Review by piiertho — APPROVED** [review]
Thanks !

**Pull request merged**
